config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations

  root 'reservations#new'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

# Validations =================================================================
	validates_presence_of :table_number, :name, :phone, 
		:start_at_time, :start_at_date, :end_at_time
	validates_numericality_of :table_number, only_integer: true
	validates :table_number, inclusion: 1..12
	validates :start_at, :end_at, overlap: {scope: "table_number"}
	validate :datetime_interval
# Callbacks ===================================================================
	before_validation :convert_to_datetime
# Scopes ======================================================================
	scope :active, -> { where( 'start_at >= ?', DateTime.now.beginning_of_day )}
# Instance methods ============================================================
	# add virtual attributes :(
	def start_at_date
	  start_at.strftime("%Y-%m-%d") if start_at.present?
	end 

	def start_at_time
	  start_at.strftime("%H:%M") if start_at.present?
	end

	def end_at_time
		end_at.strftime("%H:%M") if end_at.present?
	end

	def start_at_date= date
		return unless date.present?
	  @start_at_date = Date.parse(date).strftime("%Y-%m-%d")
	end
	def start_at_time= time
		return unless time.present?
	  @start_at_time = Time.parse(time).strftime("%H:%M")
	end

	def end_at_time= time
		return unless time.present?
		@end_at_time = Time.parse(time).strftime("%H:%M")
	end

	def convert_to_datetime
		return nil unless (@start_at_date || @start_at_time || @end_at_time)
 	  self.start_at = DateTime.parse("#{@start_at_date} #{@start_at_time}")
	  self.end_at = DateTime.parse("#{@start_at_date} #{@end_at_time}")
	end

	def datetime_interval
		return nil unless self.start_at || self.end_at
		if self.start_at > self.end_at
			errors.add :end_at, I18n.t("errors.date_interval_error")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Sad but true: i am lazy and have no time to do it without devise
  devise :database_authenticatable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_reservation_path, :notice => 'Have no access to visit this page'
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: :new
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.active.order('start_at ASC')
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def edit
  end

  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:table_number, :start_at, :end_at,
       :start_at_date, :start_at_time, :end_at_time, :name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
	def h_date date
		if date.to_date == Date.today
			date.strftime("%H:%M")
		else
			date.strftime("%F %R")
		end
	end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Restaurant
    = stylesheet_link_tag 'application', media: 'all', 
    																				'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %br/
    - if user_signed_in?
      .right= link_to('Logout', destroy_user_session_path, method: :delete)
    %h2.center
      %a{:href => "#"} Restaurant 'Vodkabar'
    = yield

app/views/reservations/_form.html.haml
= form_for @reservation, class: "form-horizontal" do |f|
  - if @reservation.errors.any?
    #error_explanation
      %ul
        - @reservation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Table #"
    = f.select :table_number, 1..12, class: "table_num form-control"
    = f.label "Date"
    = f.text_field :start_at_date, class: "datepicker form-control"
    = f.label "From "
    = f.text_field :start_at_time, class: "timepicker form-control"
    = f.label "To "
    = f.text_field :end_at_time, class: "timepicker form-control"
  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
    = f.label :phone
    = f.text_field :phone, class: "form-control"
  .field
    = f.submit 'Reserve', class: "btn btn-success"

  .field.restaurant-map
    - 12.times do |i|
      .rest-table{value: (i+1)}
        .table-numb= "# #{i+1}" 

app/views/reservations/edit.html.haml
.mymodal
	.mymodal-title
		%h4 New Reservation
	.mymodal-body
		= render 'form'

app/views/reservations/index.html.haml
.mymodal.width-800 
  .mymodal-title
    %h4 Active Reservations
  .mymodal-body
    %table.table
      %thead
        %tr
          %th Id
          %th Table #
          %th Name
          %th Phone
          %th Start at
          %th End at
          %th 
          %th
          %th
          
      %tbody
        - @reservations.each do |reservation|
          %tr
            %td= link_to reservation.id, reservation
            %td= reservation.table_number
            %td= reservation.name
            %td= reservation.phone
            %td= h_date reservation.start_at
            %td= h_date reservation.end_at
            %td= link_to 'Edit', edit_reservation_path(reservation)
            %td= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }

    %br
    .center
      = link_to 'New Reservation', new_reservation_path, class: "btn btn-success"

app/views/reservations/new.html.haml
.mymodal
	.mymodal-title
		%h4 New Reservation
	.mymodal-body
		= render 'form'

app/views/reservations/show.html.haml
.mymodal.width-800 
  .mymodal-title
    %h4= "Reservation # #{@reservation.id}"
  .mymodal-body
    %table.table
      %thead
        %tr
          %th Id
          %th.wdt12 Table #
          %th Name
          %th Phone
          %th Start at
          %th End at
          %th
          %th
          
      %tbody
        %tr
          %td= link_to @reservation.id, @reservation
          %td= @reservation.table_number
          %td= @reservation.name
          %td= @reservation.phone
          %td= h_date @reservation.start_at
          %td= h_date @reservation.end_at
          %td= link_to 'Edit', edit_reservation_path(@reservation)
          %td= link_to 'Destroy', @reservation, method: :delete, data: { confirm: 'Are you sure?' }